### ISSUE TITLE
datasource in the plugin

### ISSUE THREAD

**Issue by Biggreymoose** [yandex-cloud/grafana-logs-plugin#7] opened 2024-03-05 08:15 UTC
Good afternoon, when I tried to configure the datasource in the plugin - grafana-logs-plugin,

This error appears in Grafana, I have attached the file.

I created it through Helm chart, the plugin appeared in the installed graph, but when I clicked on it I got an error.
[grafana-plugin-error.txt](https://github.com/yandex-cloud/grafana-logs-plugin/files/14492381/grafana-plugin-error.txt)

**Comment by positiveviking** [comment] 2024-03-06 06:57
Hi.
Please can you reproduce issue using minimal environment from https://github.com/yandex-cloud/grafana-logs-plugin/tree/master/docker-private

This folder contains compose file which will build local plugin and start local grafana with basic config. If there are no issues in this installation you can try to use it as baseline for your configuration.

For now root cause of your issues with plugin is not obvious.

**Comment by Biggreymoose** [comment] 2024-03-06 15:01
Hello,
I checked, installed Grafana v9 in Dockerfile and the error was reproduced.
Maybe it's not such a big deal, maybe then I'll just update my Grafana to v10.

apply an file with error
[grafana-v9-plugin-error.txt](https://github.com/yandex-cloud/grafana-logs-plugin/files/14511607/grafana-v9-plugin-error.txt)

**Comment by positiveviking** [comment] 2024-03-07 07:49
I can confirm that config editor fails on versions prior 9.1.

So I suggest  just update your grafana. In future release incorrect grafanaDependency should be fixed for plugin.

**Closed as completed** 2024-03-07 08:51 UTC
